<?php

declare(strict_types=1);

use App\Controllers\HomeController;
use App\Controllers\AuthController;
use App\Controllers\UserController;
use App\Controllers\ClientController;
use App\Controllers\DriverController;
use App\Controllers\FleetController;
use App\Controllers\GoodsController;
use App\Controllers\DeliveryController;
use App\Controllers\DispatchingController;
use App\Controllers\DriverAppController;
use App\Controllers\LiveTrackingController;
use App\Controllers\PodController;
use App\Controllers\IncidentController;
use App\Controllers\PlanningController;
use App\Middleware\Authenticate;
use App\Middleware\GuestOnly;
use App\Middleware\VerifyCsrf;

$app->router()->get('/login', [AuthController::class, 'showLogin'], [GuestOnly::class]);
$app->router()->post('/login', [AuthController::class, 'login'], [GuestOnly::class, VerifyCsrf::class]);
$app->router()->post('/logout', [AuthController::class, 'logout'], [Authenticate::class, VerifyCsrf::class]);

$app->router()->get('/', [HomeController::class, 'index'], [Authenticate::class]);
$app->router()->get('/users', [UserController::class, 'index'], [Authenticate::class]);
$app->router()->post('/users', [UserController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/users/toggle', [UserController::class, 'toggle'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/users/{id}', [UserController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/clients', [ClientController::class, 'index'], [Authenticate::class]);
$app->router()->get('/clients/{id}', [ClientController::class, 'show'], [Authenticate::class]);
$app->router()->get('/api/clients', [ClientController::class, 'data'], [Authenticate::class]);
$app->router()->post('/api/clients', [ClientController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/clients/{id}', [ClientController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/clients/{id}/archive', [ClientController::class, 'archive'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/drivers', [DriverController::class, 'index'], [Authenticate::class]);
$app->router()->get('/drivers/{id}', [DriverController::class, 'show'], [Authenticate::class]);
$app->router()->get('/api/drivers', [DriverController::class, 'data'], [Authenticate::class]);
$app->router()->get('/drivers/{id}/photo', [DriverController::class, 'photo'], [Authenticate::class]);
$app->router()->post('/api/drivers', [DriverController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/drivers/{id}', [DriverController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/drivers/{id}/deactivate', [DriverController::class, 'deactivate'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/fleet', [FleetController::class, 'index'], [Authenticate::class]);
$app->router()->get('/fleet/{id}', [FleetController::class, 'show'], [Authenticate::class]);
$app->router()->get('/api/vehicles', [FleetController::class, 'data'], [Authenticate::class]);
$app->router()->post('/api/vehicles', [FleetController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/vehicles/{id}', [FleetController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/vehicles/{id}/deactivate', [FleetController::class, 'deactivate'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/vehicles/{id}/documents', [FleetController::class, 'addDocument'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/fleet/{id}/documents/{documentId}', [FleetController::class, 'downloadDocument'], [Authenticate::class]);
$app->router()->post('/api/vehicles/{id}/documents/{documentId}/delete', [FleetController::class, 'deleteDocument'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/goods', [GoodsController::class, 'index'], [Authenticate::class]);
$app->router()->get('/api/goods', [GoodsController::class, 'data'], [Authenticate::class]);
$app->router()->get('/api/goods/{id}', [GoodsController::class, 'detail'], [Authenticate::class]);
$app->router()->post('/api/goods', [GoodsController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/goods/{id}', [GoodsController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/goods/{id}/archive', [GoodsController::class, 'archive'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/deliveries', [DeliveryController::class, 'index'], [Authenticate::class]);
$app->router()->get('/deliveries/{id}', [DeliveryController::class, 'show'], [Authenticate::class]);
$app->router()->get('/api/deliveries', [DeliveryController::class, 'data'], [Authenticate::class]);
$app->router()->get('/api/deliveries/client/{id}/options', [DeliveryController::class, 'clientOptions'], [Authenticate::class]);
$app->router()->get('/api/deliveries/{id}/route-history', [DeliveryController::class, 'routeHistory'], [Authenticate::class]);
$app->router()->post('/api/deliveries', [DeliveryController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/deliveries/{id}', [DeliveryController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/deliveries/{id}/transition', [DeliveryController::class, 'transition'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/dispatching', [DispatchingController::class, 'index'], [Authenticate::class]);
$app->router()->get('/api/dispatching', [DispatchingController::class, 'data'], [Authenticate::class]);
$app->router()->get('/api/dispatching/{id}/resources', [DispatchingController::class, 'resources'], [Authenticate::class]);
$app->router()->post('/api/dispatching/{id}/assign', [DispatchingController::class, 'assign'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/planning', [PlanningController::class, 'index'], [Authenticate::class]);
$app->router()->get('/api/planning', [PlanningController::class, 'data'], [Authenticate::class]);
$app->router()->get('/api/planning/{id}/resources', [PlanningController::class, 'resources'], [Authenticate::class]);
$app->router()->post('/api/planning/{id}', [PlanningController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/driver-app', [DriverAppController::class, 'index'], [Authenticate::class]);
$app->router()->get('/driver-app/missions/{id}', [DriverAppController::class, 'show'], [Authenticate::class]);
$app->router()->post('/api/driver-app/missions/{id}/action', [DriverAppController::class, 'action'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/driver-app/missions/{id}/positions', [DriverAppController::class, 'positions'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/api/driver-app/missions/{id}/positions', [DriverAppController::class, 'positionHistory'], [Authenticate::class]);
$app->router()->post('/api/driver-app/missions/{id}/pod', [PodController::class, 'store'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/driver-app/missions/{id}/incident', [IncidentController::class, 'report'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/deliveries/{id}/pod.pdf', [PodController::class, 'pdf'], [Authenticate::class]);
$app->router()->get('/incidents', [IncidentController::class, 'index'], [Authenticate::class]);
$app->router()->get('/incidents/{id}', [IncidentController::class, 'show'], [Authenticate::class]);
$app->router()->get('/incidents/{id}/photos/{photoId}', [IncidentController::class, 'photo'], [Authenticate::class]);
$app->router()->get('/api/incidents', [IncidentController::class, 'data'], [Authenticate::class]);
$app->router()->post('/api/incidents/{id}', [IncidentController::class, 'update'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->post('/api/incidents/{id}/resolve', [IncidentController::class, 'resolve'], [Authenticate::class, VerifyCsrf::class]);
$app->router()->get('/live-tracking', [LiveTrackingController::class, 'index'], [Authenticate::class]);
$app->router()->get('/api/live-tracking', [LiveTrackingController::class, 'data'], [Authenticate::class]);
$app->router()->get('/api/health', [HomeController::class, 'health']);
