<?php
$client = $client ?? [];
$contacts = !empty($client['contacts']) ? $client['contacts'] : [[]];
$sites = !empty($client['sites']) ? $client['sites'] : [[]];
$recipients = !empty($client['recipients']) ? $client['recipients'] : [[]];
function clientValue(array $client, string $key, string $default=''): string { return htmlspecialchars((string)($client[$key]??$default),ENT_QUOTES,'UTF-8'); }
?>
<form class="client-form" id="<?= htmlspecialchars($formId,ENT_QUOTES,'UTF-8') ?>" data-client-form data-client-id="<?= (int)($client['id']??0) ?>">
    <nav class="form-tabs" aria-label="Sections du formulaire">
        <button type="button" class="active" data-form-tab="general">Général</button><button type="button" data-form-tab="contacts">Contacts</button><button type="button" data-form-tab="sites">Sites de livraison</button><button type="button" data-form-tab="notifications">Notifications</button>
    </nav>
    <section class="form-pane active" data-form-pane="general">
        <div class="section-title"><h3>Informations générales</h3><p>Identité, coordonnées et statut du client.</p></div>
        <div class="form-grid client-form-grid">
            <label class="field"><span>Raison sociale *</span><div><i data-lucide="building-2"></i><input name="company_name" value="<?= clientValue($client,'company_name') ?>" required maxlength="180"></div><small data-error="company_name"></small></label>
            <label class="field"><span>Dénomination légale</span><div><i data-lucide="landmark"></i><input name="legal_name" value="<?= clientValue($client,'legal_name') ?>" maxlength="180"></div></label>
            <label class="field"><span>N° fiscal</span><div><i data-lucide="file-badge"></i><input name="tax_number" value="<?= clientValue($client,'tax_number') ?>" maxlength="80"></div></label>
            <label class="field"><span>Registre de commerce</span><div><i data-lucide="file-text"></i><input name="registration_number" value="<?= clientValue($client,'registration_number') ?>" maxlength="80"></div></label>
            <label class="field"><span>E-mail</span><div><i data-lucide="mail"></i><input type="email" name="email" value="<?= clientValue($client,'email') ?>" maxlength="190"></div><small data-error="email"></small></label>
            <label class="field"><span>Téléphone</span><div><i data-lucide="phone"></i><input name="phone" value="<?= clientValue($client,'phone') ?>" maxlength="50"></div></label>
            <label class="field"><span>Site web</span><div><i data-lucide="globe"></i><input name="website" value="<?= clientValue($client,'website') ?>" maxlength="190"></div></label>
            <label class="field"><span>Statut *</span><div><i data-lucide="circle-dot"></i><select name="status"><?php foreach(['active'=>'Actif','inactive'=>'Inactif','prospect'=>'Prospect','archived'=>'Archivé'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($client['status']??'active')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div></label>
        </div>
        <div class="section-title subsection"><h3>Adresse principale</h3></div>
        <div class="form-grid client-form-grid">
            <label class="field full-span"><span>Adresse</span><div><i data-lucide="map-pin"></i><input name="address_line1" value="<?= clientValue($client,'address_line1') ?>" maxlength="190"></div></label>
            <label class="field"><span>Complément</span><div><input name="address_line2" value="<?= clientValue($client,'address_line2') ?>" maxlength="190"></div></label>
            <label class="field"><span>Ville</span><div><input name="city" value="<?= clientValue($client,'city') ?>" maxlength="100"></div></label>
            <label class="field"><span>Province</span><div><input name="province" value="<?= clientValue($client,'province') ?>" maxlength="100"></div></label>
            <label class="field"><span>Pays</span><div><input name="country" value="<?= clientValue($client,'country','RDC') ?>" maxlength="100"></div></label>
            <label class="field"><span>Latitude</span><div><i data-lucide="crosshair"></i><input type="number" step="0.0000001" name="latitude" value="<?= clientValue($client,'latitude') ?>"></div><small data-error="latitude"></small></label>
            <label class="field"><span>Longitude</span><div><i data-lucide="crosshair"></i><input type="number" step="0.0000001" name="longitude" value="<?= clientValue($client,'longitude') ?>"></div><small data-error="longitude"></small></label>
            <label class="field full-span"><span>Notes internes</span><textarea name="notes" rows="3"><?= clientValue($client,'notes') ?></textarea></label>
        </div>
    </section>
    <section class="form-pane" data-form-pane="contacts"><div class="section-title with-action"><div><h3>Contacts</h3><p>Interlocuteurs rattachés à cette organisation.</p></div><button type="button" class="button button-secondary" data-add-row="contacts"><i data-lucide="plus"></i> Ajouter</button></div><div class="repeater" data-repeater="contacts"><?php foreach($contacts as $row): ?><div class="repeater-row"><div class="repeater-grid"><label class="field"><span>Nom complet *</span><div><input data-field="full_name" value="<?= clientValue($row,'full_name') ?>"></div></label><label class="field"><span>Fonction</span><div><input data-field="job_title" value="<?= clientValue($row,'job_title') ?>"></div></label><label class="field"><span>E-mail</span><div><input type="email" data-field="email" value="<?= clientValue($row,'email') ?>"></div></label><label class="field"><span>Téléphone</span><div><input data-field="phone" value="<?= clientValue($row,'phone') ?>"></div></label></div><label class="check-field"><input type="checkbox" data-field="is_primary" <?= !empty($row['is_primary'])?'checked':'' ?>> Contact principal</label><button type="button" class="remove-row" aria-label="Supprimer"><i data-lucide="trash-2"></i></button></div><?php endforeach; ?></div></section>
    <section class="form-pane" data-form-pane="sites"><div class="section-title with-action"><div><h3>Sites de livraison</h3><p>Adresses opérationnelles et coordonnées GPS.</p></div><button type="button" class="button button-secondary" data-add-row="sites"><i data-lucide="plus"></i> Ajouter</button></div><small class="form-error" data-error="sites"></small><div class="repeater" data-repeater="sites"><?php foreach($sites as $row): ?><div class="repeater-row"><div class="repeater-grid three"><label class="field"><span>Nom du site *</span><div><input data-field="name" value="<?= clientValue($row,'name') ?>"></div></label><label class="field"><span>Code</span><div><input data-field="site_code" value="<?= clientValue($row,'site_code') ?>"></div></label><label class="field"><span>Ville *</span><div><input data-field="city" value="<?= clientValue($row,'city') ?>"></div></label><label class="field wide"><span>Adresse *</span><div><input data-field="address_line1" value="<?= clientValue($row,'address_line1') ?>"></div></label><label class="field"><span>Province</span><div><input data-field="province" value="<?= clientValue($row,'province') ?>"></div></label><label class="field"><span>Latitude</span><div><input type="number" step=".0000001" data-field="latitude" value="<?= clientValue($row,'latitude') ?>"></div></label><label class="field"><span>Longitude</span><div><input type="number" step=".0000001" data-field="longitude" value="<?= clientValue($row,'longitude') ?>"></div></label><label class="field wide"><span>Instructions de livraison</span><div><input data-field="delivery_instructions" value="<?= clientValue($row,'delivery_instructions') ?>"></div></label><input type="hidden" data-field="country" value="<?= clientValue($row,'country','RDC') ?>"><input type="hidden" data-field="status" value="<?= clientValue($row,'status','active') ?>"></div><label class="check-field"><input type="checkbox" data-field="is_default" <?= !empty($row['is_default'])?'checked':'' ?>> Site par défaut</label><button type="button" class="remove-row" aria-label="Supprimer"><i data-lucide="trash-2"></i></button></div><?php endforeach; ?></div></section>
    <section class="form-pane" data-form-pane="notifications"><div class="section-title with-action"><div><h3>Personnes à notifier</h3><p>Destinataires des événements de livraison.</p></div><button type="button" class="button button-secondary" data-add-row="recipients"><i data-lucide="plus"></i> Ajouter</button></div><div class="repeater" data-repeater="recipients"><?php foreach($recipients as $row): ?><div class="repeater-row"><div class="repeater-grid"><label class="field"><span>Nom complet *</span><div><input data-field="full_name" value="<?= clientValue($row,'full_name') ?>"></div></label><label class="field"><span>E-mail</span><div><input type="email" data-field="email" value="<?= clientValue($row,'email') ?>"></div></label><label class="field"><span>Téléphone</span><div><input data-field="phone" value="<?= clientValue($row,'phone') ?>"></div></label><label class="field"><span>Événements</span><div><select data-field="notify_on"><option value="dispatch,arrival,delivery">Tous les événements</option><option value="dispatch">Expédition</option><option value="arrival,delivery">Arrivée et livraison</option></select></div></label></div><div class="inline-checks"><label class="check-field"><input type="checkbox" data-field="notify_email" <?= !isset($row['notify_email'])||!empty($row['notify_email'])?'checked':'' ?>> E-mail</label><label class="check-field"><input type="checkbox" data-field="notify_sms" <?= !empty($row['notify_sms'])?'checked':'' ?>> SMS</label></div><button type="button" class="remove-row" aria-label="Supprimer"><i data-lucide="trash-2"></i></button></div><?php endforeach; ?></div></section>
    <div class="modal-actions client-form-actions"><button type="button" class="button button-secondary" data-modal-close>Annuler</button><button type="submit" class="button button-primary"><i data-lucide="save"></i> <?= !empty($client['id'])?'Enregistrer les modifications':'Créer le client' ?></button></div>
</form>
