<?php
$delivery=$delivery??[];$destinations=$delivery['destinations']??[[]];$allGoods=$delivery['goods']??[];$pageMode=$pageMode??false;$cancelUrl=$cancelUrl??'';
function deliveryValue(array $data,string $key): string{return htmlspecialchars((string)($data[$key]??''),ENT_QUOTES,'UTF-8');}
$goodsByDestination=[];foreach($allGoods as $goods){$order=max(1,(int)($goods['destination_order']??1));$goodsByDestination[$order][]=$goods;}
?>
<form id="<?= htmlspecialchars($formId,ENT_QUOTES,'UTF-8') ?>" data-delivery-form data-delivery-id="<?= (int)($delivery['id']??0) ?>" class="delivery-form">
<div class="delivery-form-body">
<div class="form-section course-info-section"><div class="section-title course-section-title"><div><span class="section-kicker"><i data-lucide="route"></i> Paramètres généraux</span><h3>Informations de la course</h3><p>Ces informations s’appliquent à l’ensemble des destinations.</p></div><span class="required-legend"><b>*</b> Champs obligatoires</span></div><div class="form-grid delivery-form-grid course-fields-grid">
<label class="field course-field-card client-course-field"><span class="course-field-icon"><i data-lucide="building-2"></i></span><span class="course-field-content"><span class="course-field-label">Client <b>*</b></span><span class="course-field-control"><select name="client_id" required><option value="">Sélectionner un client</option><?php foreach($clients as $client): ?><option value="<?= (int)$client['id'] ?>" <?= (int)($delivery['client_id']??0)===(int)$client['id']?'selected':'' ?>><?= htmlspecialchars($client['company_name'].' · '.$client['code'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></span><small>Entreprise pour laquelle la course est organisée</small><em data-error="client_id"></em></span></label>
<label class="field course-field-card"><span class="course-field-icon"><i data-lucide="calendar-clock"></i></span><span class="course-field-content"><span class="course-field-label">Date et heure prévues <b>*</b></span><span class="course-field-control"><input type="datetime-local" name="scheduled_at" value="<?= !empty($delivery['scheduled_at'])?date('Y-m-d\TH:i',strtotime($delivery['scheduled_at'])):'' ?>" required></span><small>Moment prévu pour le démarrage de l’opération</small><em data-error="scheduled_at"></em></span></label>
<label class="field course-field-card priority-course-field"><span class="course-field-icon"><i data-lucide="flag"></i></span><span class="course-field-content"><span class="course-field-label">Niveau de priorité <b>*</b></span><span class="course-field-control"><select name="priority"><?php foreach(['Basse','Normale','Haute','Urgente'] as $priority): ?><option <?= ($delivery['priority']??'Normale')===$priority?'selected':'' ?>><?= $priority ?></option><?php endforeach; ?></select></span><small>Détermine l’ordre de traitement par les équipes</small></span></label>
</div></div>
<div class="form-section delivery-stops-section"><div class="section-title with-action"><div><h3>Itinéraire et chargement</h3><p>Complétez chaque destination puis ajoutez directement ce qui doit y être livré.</p></div><button type="button" class="button button-secondary" data-add-stop><i data-lucide="map-pin-plus"></i> Ajouter une destination</button></div>
<div class="delivery-stops" data-delivery-stops>
<?php foreach(array_values($destinations) as $index=>$destination): $destinationGoods=$goodsByDestination[$index+1]??[[]]; ?>
<article class="delivery-stop-card" data-stop-card data-stop-uid="stop-<?= $index+1 ?>">
<header class="stop-card-head"><div class="stop-identity"><span class="stop-number" data-stop-number><?= $index+1 ?></span><div><small>ARRÊT <b data-stop-order><?= $index+1 ?></b></small><strong data-stop-summary><?= deliveryValue($destination,'label')?:'Nouvelle destination' ?></strong><p data-stop-meta>À compléter</p></div></div><div class="stop-actions"><button type="button" data-stop-toggle aria-label="Replier la destination" title="Replier"><i data-lucide="chevron-up"></i></button><button type="button" data-stop-up aria-label="Monter la destination" title="Monter"><i data-lucide="arrow-up"></i></button><button type="button" data-stop-down aria-label="Descendre la destination" title="Descendre"><i data-lucide="arrow-down"></i></button><button type="button" data-remove-stop class="danger" aria-label="Supprimer la destination" title="Supprimer"><i data-lucide="trash-2"></i></button></div></header>
<div class="stop-card-body" data-stop-body><div class="stop-fields-grid">
<label class="field"><span>Nom du lieu *</span><input type="text" maxlength="160" data-destination-field="label" value="<?= deliveryValue($destination,'label') ?>" placeholder="Ex. Agence Kenya" required></label>
<label class="field"><span>Ville</span><input type="text" maxlength="120" data-destination-field="city" value="<?= deliveryValue($destination,'city') ?>" placeholder="Lubumbashi"></label>
<label class="field full-span"><span>Adresse complète *</span><input type="text" maxlength="255" data-destination-field="address" value="<?= deliveryValue($destination,'address_line') ?>" placeholder="Avenue, numéro, quartier et repère" required></label>
<label class="field"><span>Contact sur place</span><input type="text" maxlength="160" data-destination-field="contact_name" value="<?= deliveryValue($destination,'contact_name') ?>" placeholder="Nom du réceptionnaire"></label>
<label class="field"><span>Téléphone</span><input type="tel" maxlength="60" data-destination-field="contact_phone" value="<?= deliveryValue($destination,'contact_phone') ?>" placeholder="+243…"></label>
<label class="field full-span"><span>Instructions de livraison</span><textarea rows="2" maxlength="2000" data-destination-field="instructions" placeholder="Accès, quai, horaires ou consigne particulière"><?= deliveryValue($destination,'instructions') ?></textarea></label>
</div>
<section class="stop-goods"><div class="stop-goods-head"><div><span><i data-lucide="boxes"></i></span><div><strong>Marchandises à livrer ici</strong><small>Chaque ligne restera attachée à cette destination.</small></div></div><button type="button" class="button button-secondary compact" data-add-stop-goods><i data-lucide="plus"></i> Ajouter une ligne</button></div>
<div class="stop-goods-table-wrap"><table class="stop-goods-table"><thead><tr><th>Désignation *</th><th>Quantité *</th><th>Unité *</th><th>Poids/unité</th><th>Poids total</th><th></th></tr></thead><tbody data-stop-goods><?php foreach($destinationGoods as $goods): ?><tr class="stop-goods-row" data-goods-row><td data-label="Désignation"><input type="text" maxlength="255" data-goods-field="description" value="<?= deliveryValue($goods,'description_snapshot') ?>" placeholder="Ex. Cartons de pièces"></td><td data-label="Quantité"><input type="number" step="0.001" min="0.001" data-goods-field="quantity" value="<?= deliveryValue($goods,'quantity') ?>" placeholder="0"></td><td data-label="Unité"><input type="text" maxlength="30" data-goods-field="unit" value="<?= deliveryValue($goods,'unit') ?>" placeholder="carton"></td><td data-label="Poids/unité"><input type="number" step="0.001" min="0.001" data-goods-field="unit_weight_kg" value="<?= deliveryValue($goods,'unit_weight_kg') ?>" placeholder="kg"></td><td data-label="Poids total"><strong data-line-weight>—</strong></td><td><button type="button" data-remove-stop-goods aria-label="Supprimer la marchandise"><i data-lucide="trash-2"></i></button></td></tr><?php endforeach; ?></tbody></table></div>
<div class="stop-goods-foot"><small data-stop-goods-error></small><span><b data-stop-goods-count>0</b> ligne(s) · <strong data-stop-weight>0 kg</strong></span></div></section>
</div></article><?php endforeach; ?>
</div><small class="form-error" data-error="destinations"></small><small class="form-error" data-error="goods"></small>
<button type="button" class="add-stop-wide" data-add-stop><i data-lucide="plus-circle"></i><span><strong>Ajouter une autre destination</strong><small>Créer le prochain arrêt et son chargement</small></span></button></div>
<div class="form-section"><div class="section-title"><h3>Affectation</h3><p>Le chauffeur et le véhicule peuvent être renseignés maintenant ou pendant le dispatching.</p></div><div class="form-grid delivery-form-grid"><label class="field"><span>Chauffeur</span><select name="driver_id"><option value="">Non affecté</option><?php foreach($drivers as $driver): ?><option value="<?= (int)$driver['id'] ?>" <?= (int)($delivery['driver_id']??0)===(int)$driver['id']?'selected':'' ?>><?= htmlspecialchars($driver['first_name'].' '.$driver['last_name'].' · '.$driver['status'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label class="field"><span>Véhicule</span><select name="vehicle_id"><option value="">Non affecté</option><?php foreach($vehicles as $vehicle): ?><option value="<?= (int)$vehicle['id'] ?>" data-driver="<?= (int)($vehicle['assigned_driver_id']??0) ?>" <?= (int)($delivery['vehicle_id']??0)===(int)$vehicle['id']?'selected':'' ?>><?= htmlspecialchars($vehicle['registration_number'].' · '.$vehicle['brand'].' '.$vehicle['model'].' · '.$vehicle['status'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label class="field full-span"><span>Observations générales</span><textarea name="observations" rows="3" placeholder="Informations concernant l’ensemble de la course"><?= deliveryValue($delivery,'observations') ?></textarea></label></div></div>
</div><div class="modal-actions delivery-form-actions"><div class="form-live-summary"><span><i data-lucide="map-pin"></i><b data-form-stop-count><?= count($destinations) ?></b> destination(s)</span><span><i data-lucide="package"></i><b data-form-goods-count>0</b> marchandise(s)</span><span><i data-lucide="weight"></i><b data-form-weight>0 kg</b></span></div><?php if($pageMode): ?><a href="<?= htmlspecialchars($cancelUrl,ENT_QUOTES,'UTF-8') ?>" class="button button-secondary">Annuler</a><?php else: ?><button type="button" class="button button-secondary" data-modal-close>Annuler</button><?php endif; ?><button type="submit" class="button button-primary"><i data-lucide="save"></i> <?= !empty($delivery['id'])?'Enregistrer les modifications':'Créer le brouillon' ?></button></div></form>
