<?php use App\Core\Env; use App\Core\View; $baseUrl=rtrim((string)Env::get('APP_URL',''),'/'); ?>
<div class="page-heading dashboard-heading direction-heading"><div><span class="eyebrow">Aujourd’hui · <?= date('d/m/Y') ?></span><h1>Tableau de bord Direction</h1><p>Situation opérationnelle en temps réel et indicateurs des 30 derniers jours.</p></div><div class="heading-actions"><a class="button button-secondary" href="<?= $baseUrl ?>/live-tracking"><i data-lucide="radio-tower"></i> Suivi en direct</a><a class="button button-primary" href="<?= $baseUrl ?>/deliveries"><i data-lucide="package-search"></i> Voir les livraisons</a></div></div>

<section class="direction-kpis" aria-label="Indicateurs opérationnels">
<?php $cards=[['deliveries_today','Livraisons du jour','calendar-check-2','primary','Planifiées aujourd’hui'],['to_prepare','À préparer','package-open','neutral','Action logistique requise'],['ready','Prêtes','badge-check','success','Disponibles au chargement'],['in_transit','En transit','route','info','Actuellement sur route'],['delivered_today','Livrées','package-check','success','Confirmées aujourd’hui'],['overdue','En retard','clock-alert','danger','Échéance dépassée'],['open_incidents','Incidents ouverts','triangle-alert','danger','Non résolus'],['available_drivers','Chauffeurs disponibles','contact-round','resource','Mobilisables maintenant'],['available_vehicles','Véhicules disponibles','truck','resource','Mobilisables maintenant']];foreach($cards as $card): ?><a class="direction-kpi <?= $card[3] ?>" href="<?= in_array($card[0],['open_incidents'],true)?$baseUrl.'/incidents':(in_array($card[0],['available_drivers'],true)?$baseUrl.'/drivers':(in_array($card[0],['available_vehicles'],true)?$baseUrl.'/fleet':$baseUrl.'/deliveries')) ?>"><span><i data-lucide="<?= $card[2] ?>"></i></span><div><small><?= $card[1] ?></small><strong><?= (int)$kpis[$card[0]] ?></strong><p><?= $card[4] ?></p></div><i data-lucide="chevron-right"></i></a><?php endforeach; ?>
</section>

<?php if((int)$kpis['overdue']>0||(int)$kpis['open_incidents']>0): ?><section class="direction-alert"><i data-lucide="circle-alert"></i><div><strong>Attention requise</strong><p><b><?= (int)$kpis['overdue'] ?></b> livraison(s) en retard et <b><?= (int)$kpis['open_incidents'] ?></b> incident(s) non résolu(s).</p></div><a href="#attentionOperations">Examiner les priorités <i data-lucide="arrow-down"></i></a></section><?php endif; ?>

<section class="direction-chart-grid">
    <article class="panel chart-panel wide"><div class="panel-head"><div><h2>Livraisons par période</h2><p>Planifiées et effectivement livrées · 14 derniers jours</p></div><span class="data-period">14 jours</span></div><div class="direction-chart large"><canvas id="periodDeliveriesChart"></canvas></div></article>
    <article class="panel chart-panel punctuality-panel"><div class="panel-head"><div><h2>Livraison à temps</h2><p>Livraisons terminées · 30 jours</p></div></div><div class="punctuality-content"><div class="direction-chart doughnut"><canvas id="punctualityChart"></canvas><div><strong><?= number_format((float)$punctuality['rate'],1,',',' ') ?>%</strong><span>à temps</span></div></div><dl><div><dt>À temps</dt><dd><?= (int)$punctuality['on_time'] ?></dd></div><div><dt>En retard</dt><dd><?= (int)$punctuality['late'] ?></dd></div><div><dt>Total analysé</dt><dd><?= (int)$punctuality['total'] ?></dd></div></dl></div></article>
    <article class="panel chart-panel"><div class="panel-head"><div><h2>Incidents</h2><p>Répartition par type · 30 jours</p></div><a class="panel-link" href="<?= $baseUrl ?>/incidents">Détails <i data-lucide="arrow-up-right"></i></a></div><div class="direction-chart medium"><canvas id="incidentTypesChart"></canvas></div></article>
    <article class="panel chart-panel"><div class="panel-head"><div><h2>Performance opérationnelle</h2><p>Réalisation, ponctualité et disponibilité</p></div><span class="data-period">Objectif 100%</span></div><div class="direction-chart medium"><canvas id="operationalPerformanceChart"></canvas></div></article>
</section>

<section class="direction-operations" id="attentionOperations">
    <article class="panel direction-list-panel"><div class="panel-head"><div><h2>Livraisons en retard</h2><p>Priorisées par urgence et ancienneté</p></div><a class="panel-link" href="<?= $baseUrl ?>/deliveries">Toutes <i data-lucide="arrow-up-right"></i></a></div><?php if(!$attention): ?><div class="direction-empty"><i data-lucide="shield-check"></i><strong>Aucun retard opérationnel</strong><span>Toutes les échéances sont maîtrisées.</span></div><?php else: ?><div class="attention-list"><?php foreach($attention as $delivery): ?><a href="<?= $baseUrl ?>/deliveries/<?= (int)$delivery['id'] ?>"><span class="delay-icon"><i data-lucide="clock-alert"></i></span><div><strong><?= htmlspecialchars($delivery['reference'].' · '.$delivery['company_name'],ENT_QUOTES,'UTF-8') ?></strong><p><?= htmlspecialchars($delivery['site_name'].' · '.(trim($delivery['driver_name'])?:'Non affecté'),ENT_QUOTES,'UTF-8') ?></p></div><time><?= (int)floor((int)$delivery['delay_minutes']/60) ?> h <?= (int)$delivery['delay_minutes']%60 ?> min</time><?= View::partial('components/status-badge',['status'=>$delivery['status']]) ?></a><?php endforeach; ?></div><?php endif; ?></article>
    <article class="panel direction-list-panel"><div class="panel-head"><div><h2>Programme du jour</h2><p>Livraisons prévues aujourd’hui</p></div><span class="data-period"><?= count($today) ?> opération(s)</span></div><?php if(!$today): ?><div class="direction-empty"><i data-lucide="calendar-check"></i><strong>Aucune livraison planifiée</strong><span>Le programme du jour est vide.</span></div><?php else: ?><div class="today-list"><?php foreach($today as $delivery): ?><a href="<?= $baseUrl ?>/deliveries/<?= (int)$delivery['id'] ?>"><time><?= date('H:i',strtotime($delivery['scheduled_at'])) ?></time><div><strong><?= htmlspecialchars($delivery['reference'].' · '.$delivery['company_name'],ENT_QUOTES,'UTF-8') ?></strong><p><?= htmlspecialchars($delivery['site_name'].' · '.(trim($delivery['driver_name'])?:'Non affecté'),ENT_QUOTES,'UTF-8') ?></p></div><?= View::partial('components/status-badge',['status'=>$delivery['status']]) ?></a><?php endforeach; ?></div><?php endif; ?></article>
</section>

<script>window.MSS_DASHBOARD=<?= json_encode(['period'=>$period,'punctuality'=>$punctuality,'incidents'=>$incidents,'performance'=>$performance],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script>
