CREATE TABLE IF NOT EXISTS delivery_pods (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    delivery_id BIGINT UNSIGNED NOT NULL,
    recipient_name VARCHAR(160) NOT NULL,
    observations TEXT NULL,
    signature_mime VARCHAR(40) NOT NULL DEFAULT 'image/jpeg',
    signature_data MEDIUMBLOB NOT NULL,
    delivery_photo_mime VARCHAR(40) NOT NULL DEFAULT 'image/jpeg',
    delivery_photo_data MEDIUMBLOB NOT NULL,
    signed_note_mime VARCHAR(40) NULL,
    signed_note_data MEDIUMBLOB NULL,
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(11,7) NOT NULL,
    accuracy_m DECIMAL(10,2) NOT NULL,
    captured_at DATETIME NOT NULL,
    driver_id BIGINT UNSIGNED NOT NULL,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_delivery_pod (delivery_id),
    KEY idx_pod_captured_at (captured_at),
    CONSTRAINT fk_pod_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_driver FOREIGN KEY (driver_id) REFERENCES drivers (id),
    CONSTRAINT fk_pod_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id),
    CONSTRAINT fk_pod_user FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
