<?php $driver=$driver??[]; function driverValue(array $d,string $key): string{return htmlspecialchars((string)($d[$key]??''),ENT_QUOTES,'UTF-8');} ?>
<form id="<?= htmlspecialchars($formId,ENT_QUOTES,'UTF-8') ?>" data-driver-form data-driver-id="<?= (int)($driver['id']??0) ?>" class="driver-form" enctype="multipart/form-data">
    <div class="driver-form-layout">
        <aside class="photo-upload-block"><div class="photo-preview" data-photo-preview><?php if(!empty($driver['has_photo'])): ?><img src="<?= rtrim((string)App\Core\Env::get('APP_URL',''),'/').'/drivers/'.(int)$driver['id'].'/photo' ?>" alt="Photo du chauffeur"><?php else: ?><i data-lucide="user-round"></i><?php endif; ?></div><label class="button button-secondary photo-button"><i data-lucide="camera"></i> Choisir une photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" hidden></label><small>JPG, PNG ou WebP · 3 Mo max.</small><small class="field-error" data-error="photo"></small></aside>
        <div class="driver-fields"><div class="form-section"><div class="section-title"><h3>Identité</h3><p>Informations personnelles et coordonnées.</p></div><div class="form-grid driver-form-grid">
            <label class="field"><span>Prénom *</span><div><i data-lucide="user"></i><input name="first_name" value="<?= driverValue($driver,'first_name') ?>" required></div><small data-error="first_name"></small></label><label class="field"><span>Nom *</span><div><i data-lucide="user"></i><input name="last_name" value="<?= driverValue($driver,'last_name') ?>" required></div><small data-error="last_name"></small></label>
            <label class="field"><span>Date de naissance</span><div><i data-lucide="calendar"></i><input type="date" name="date_of_birth" value="<?= driverValue($driver,'date_of_birth') ?>"></div><small data-error="date_of_birth"></small></label><label class="field"><span>Genre</span><div><select name="gender"><option value="">Non précisé</option><option <?= ($driver['gender']??'')==='Homme'?'selected':'' ?>>Homme</option><option <?= ($driver['gender']??'')==='Femme'?'selected':'' ?>>Femme</option><option <?= ($driver['gender']??'')==='Autre'?'selected':'' ?>>Autre</option></select></div></label>
            <label class="field"><span>Téléphone *</span><div><i data-lucide="phone"></i><input name="phone" value="<?= driverValue($driver,'phone') ?>" required></div><small data-error="phone"></small></label><label class="field"><span>Téléphone secondaire</span><div><i data-lucide="phone-call"></i><input name="alternate_phone" value="<?= driverValue($driver,'alternate_phone') ?>"></div></label>
            <label class="field"><span>E-mail</span><div><i data-lucide="mail"></i><input type="email" name="email" value="<?= driverValue($driver,'email') ?>"></div><small data-error="email"></small></label><label class="field"><span>Ville</span><div><i data-lucide="map-pin"></i><input name="city" value="<?= driverValue($driver,'city') ?>"></div></label><label class="field full-span"><span>Compte de l’application mobile</span><div><i data-lucide="smartphone"></i><select name="user_id"><option value="">Aucun compte lié</option><?php foreach(($mobileUsers??[]) as $mobileUser): ?><option value="<?= (int)$mobileUser['id'] ?>" <?= (int)($driver['user_id']??0)===(int)$mobileUser['id']?'selected':'' ?>><?= htmlspecialchars($mobileUser['name'].' · '.$mobileUser['email'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><small>Seuls les comptes ayant le rôle Chauffeur sont proposés.</small></label><label class="field full-span"><span>Adresse</span><div><i data-lucide="map"></i><input name="address" value="<?= driverValue($driver,'address') ?>"></div></label>
        </div></div><div class="form-section"><div class="section-title"><h3>Permis et disponibilité</h3><p>Habilitations et situation opérationnelle.</p></div><div class="form-grid driver-form-grid">
            <label class="field"><span>Numéro de permis *</span><div><i data-lucide="badge-check"></i><input name="license_number" value="<?= driverValue($driver,'license_number') ?>" required></div><small data-error="license_number"></small></label><label class="field"><span>Catégorie *</span><div><i data-lucide="badge"></i><select name="license_category" required><option value="">Sélectionner</option><?php foreach(['A','B','C','D','BE','CE','DE'] as $category): ?><option <?= ($driver['license_category']??'')===$category?'selected':'' ?>><?= $category ?></option><?php endforeach; ?></select></div><small data-error="license_category"></small></label>
            <label class="field"><span>Date de délivrance</span><div><i data-lucide="calendar-check"></i><input type="date" name="license_issued_at" value="<?= driverValue($driver,'license_issued_at') ?>"></div><small data-error="license_issued_at"></small></label><label class="field"><span>Expiration *</span><div><i data-lucide="calendar-clock"></i><input type="date" name="license_expires_at" value="<?= driverValue($driver,'license_expires_at') ?>" required></div><small data-error="license_expires_at"></small></label>
            <label class="field"><span>Statut *</span><div><i data-lucide="activity"></i><select name="status"><?php foreach(['Disponible','Affecté','En mission','Indisponible'] as $status): ?><option <?= ($driver['status']??'Disponible')===$status?'selected':'' ?>><?= $status ?></option><?php endforeach; ?></select></div><small data-error="status"></small></label><label class="field"><span>Disponible à partir de</span><div><i data-lucide="clock"></i><input type="datetime-local" name="available_from" value="<?= !empty($driver['available_from'])?htmlspecialchars(date('Y-m-d\TH:i',strtotime($driver['available_from'])),ENT_QUOTES,'UTF-8'):'' ?>"></div></label>
        </div></div><div class="form-section"><div class="section-title"><h3>Contact d’urgence</h3></div><div class="form-grid driver-form-grid"><label class="field"><span>Nom complet</span><div><i data-lucide="contact-round"></i><input name="emergency_contact_name" value="<?= driverValue($driver,'emergency_contact_name') ?>"></div></label><label class="field"><span>Téléphone</span><div><i data-lucide="phone-call"></i><input name="emergency_contact_phone" value="<?= driverValue($driver,'emergency_contact_phone') ?>"></div></label><label class="field full-span"><span>Notes internes</span><textarea name="notes" rows="3"><?= driverValue($driver,'notes') ?></textarea></label></div></div></div>
    </div><div class="modal-actions driver-form-actions"><button type="button" class="button button-secondary" data-modal-close>Annuler</button><button type="submit" class="button button-primary"><i data-lucide="save"></i> <?= !empty($driver['id'])?'Enregistrer':'Créer le chauffeur' ?></button></div>
</form>
