<?php

declare(strict_types=1);

namespace App\Models;

use App\Core\Auth;
use App\Core\Database;
use PDO;
use RuntimeException;
use Throwable;

final class Delivery
{
    public const FLOW=['Brouillon','À préparer','Prête','Chargement','Chargée','Partie','En transit','Arrivée','Livrée','Clôturée'];
    public const EXCEPTIONS=['Incident','Annulée'];

    public static function listing(array $filters): array
    {
        $where=['1=1'];$params=[];if(($filters['status']??'')!==''){$where[]='d.status=:status';$params['status']=$filters['status'];}if(($filters['priority']??'')!==''){$where[]='d.priority=:priority';$params['priority']=$filters['priority'];}if(($filters['client_id']??'')!==''){$where[]='d.client_id=:client';$params['client']=(int)$filters['client_id'];}if(($filters['date_from']??'')!==''){$where[]='DATE(d.scheduled_at)>=:date_from';$params['date_from']=$filters['date_from'];}if(($filters['date_to']??'')!==''){$where[]='DATE(d.scheduled_at)<=:date_to';$params['date_to']=$filters['date_to'];}if(($filters['search']??'')!==''){$term='%'.$filters['search'].'%';$where[]='(d.reference LIKE :s1 OR c.company_name LIKE :s2 OR s.name LIKE :s3 OR CONCAT(dr.first_name," ",dr.last_name) LIKE :s4 OR v.registration_number LIKE :s5)';foreach(['s1','s2','s3','s4','s5'] as $key){$params[$key]=$term;}}
        $sql='SELECT d.id,d.reference,d.scheduled_at,d.priority,d.status,d.updated_at,c.company_name,s.name site_name,s.city,dr.first_name driver_first_name,dr.last_name driver_last_name,v.registration_number,COUNT(dg.id) goods_count,COALESCE(SUM(dg.quantity*COALESCE(dg.unit_weight_kg,0)),0) total_weight_kg,EXISTS(SELECT 1 FROM delivery_pods pod WHERE pod.delivery_id=d.id) has_pod FROM deliveries d JOIN clients c ON c.id=d.client_id JOIN client_sites s ON s.id=d.client_site_id LEFT JOIN drivers dr ON dr.id=d.driver_id LEFT JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN delivery_goods dg ON dg.delivery_id=d.id WHERE '.implode(' AND ',$where).' GROUP BY d.id ORDER BY d.scheduled_at DESC,d.id DESC';$statement=Database::connection()->prepare($sql);$statement->execute($params);return $statement->fetchAll();
    }

    public static function find(int $id): ?array
    {
        $sql='SELECT d.*,c.company_name,c.code client_code,s.name site_name,s.address_line1 site_address,s.city site_city,s.latitude site_latitude,s.longitude site_longitude,s.delivery_instructions,ct.full_name contact_name,ct.email contact_email,ct.phone contact_phone,dr.first_name driver_first_name,dr.last_name driver_last_name,dr.phone driver_phone,v.registration_number,v.brand vehicle_brand,v.model vehicle_model,u.name creator_name FROM deliveries d JOIN clients c ON c.id=d.client_id JOIN client_sites s ON s.id=d.client_site_id LEFT JOIN client_contacts ct ON ct.id=d.client_contact_id LEFT JOIN drivers dr ON dr.id=d.driver_id LEFT JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN users u ON u.id=d.created_by WHERE d.id=:id';$s=Database::connection()->prepare($sql);$s->execute(['id'=>$id]);$d=$s->fetch();if(!$d){return null;}$g=Database::connection()->prepare('SELECT dg.*,g.reference FROM delivery_goods dg LEFT JOIN goods g ON g.id=dg.goods_id WHERE dg.delivery_id=:id ORDER BY dg.id');$g->execute(['id'=>$id]);$d['goods']=$g->fetchAll();$h=Database::connection()->prepare('SELECT h.*,u.name user_name FROM delivery_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.delivery_id=:id ORDER BY h.changed_at,h.id');$h->execute(['id'=>$id]);$d['timeline']=$h->fetchAll();$d['pod']=DeliveryPod::summary($id);return $d;
    }

    public static function clients(): array{return Database::connection()->query("SELECT id,code,company_name FROM clients WHERE status IN ('active','prospect') ORDER BY company_name")->fetchAll();}
    public static function goodsCatalog(): array{return Database::connection()->query("SELECT id,reference,designation,unit,unit_weight_kg FROM goods WHERE status='Actif' ORDER BY designation")->fetchAll();}
    public static function drivers(): array{return Database::connection()->query("SELECT id,first_name,last_name,status FROM drivers WHERE is_active=1 ORDER BY last_name,first_name")->fetchAll();}
    public static function vehicles(): array{return Database::connection()->query("SELECT id,registration_number,brand,model,status,assigned_driver_id FROM vehicles WHERE is_active=1 ORDER BY registration_number")->fetchAll();}
    public static function clientOptions(int $clientId): array{$sites=Database::connection()->prepare("SELECT id,name,address_line1,city,latitude,longitude,is_default FROM client_sites WHERE client_id=:id AND status='active' ORDER BY is_default DESC,name");$sites->execute(['id'=>$clientId]);$contacts=Database::connection()->prepare('SELECT id,full_name,job_title,email,phone,is_primary FROM client_contacts WHERE client_id=:id ORDER BY is_primary DESC,full_name');$contacts->execute(['id'=>$clientId]);return ['sites'=>$sites->fetchAll(),'contacts'=>$contacts->fetchAll()];}

    public static function create(array $data): int
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{self::assertRelations($pdo,$data);$reference=self::nextReference($pdo);$p=self::params($data);$p['reference']=$reference;$p['created_by']=Auth::id();$p['updated_by']=Auth::id();$sql='INSERT INTO deliveries (reference,client_id,client_site_id,client_contact_id,scheduled_at,priority,driver_id,vehicle_id,status,observations,created_by,updated_by) VALUES (:reference,:client_id,:client_site_id,:client_contact_id,:scheduled_at,:priority,:driver_id,:vehicle_id,"Brouillon",:observations,:created_by,:updated_by)';$pdo->prepare($sql)->execute($p);$id=(int)$pdo->lastInsertId();self::replaceGoods($pdo,$id,$data['goods']??[]);self::logStatus($pdo,$id,null,'Brouillon','Livraison créée');self::syncResources($pdo,$id,'Brouillon',$data);$pdo->commit();return $id;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function update(int $id,array $data): bool
    {
        $old=self::find($id);if(!$old){return false;}if(!in_array($old['status'],['Brouillon','À préparer','Prête','Chargement','Chargée'],true)){throw new RuntimeException('Cette livraison ne peut plus être modifiée après son départ.');}$pdo=Database::connection();$pdo->beginTransaction();try{self::assertRelations($pdo,$data);$p=self::params($data);$p['id']=$id;$p['updated_by']=Auth::id();$sql='UPDATE deliveries SET client_id=:client_id,client_site_id=:client_site_id,client_contact_id=:client_contact_id,scheduled_at=:scheduled_at,priority=:priority,driver_id=:driver_id,vehicle_id=:vehicle_id,observations=:observations,updated_by=:updated_by WHERE id=:id';$pdo->prepare($sql)->execute($p);self::replaceGoods($pdo,$id,$data['goods']??[]);if($old['driver_id']&&(int)$old['driver_id']!==(int)($data['driver_id']??0)){$pdo->prepare("UPDATE drivers SET status='Disponible',updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$old['driver_id']]);}if($old['vehicle_id']&&(int)$old['vehicle_id']!==(int)($data['vehicle_id']??0)){$pdo->prepare("UPDATE vehicles SET status='Disponible',assigned_driver_id=NULL,updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$old['vehicle_id']]);}self::syncResources($pdo,$id,$old['status'],$data);$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function transition(int $id,string $target,?string $comment): array
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM deliveries WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$d=$s->fetch();if(!$d){throw new RuntimeException('Livraison introuvable.');}$from=$d['status'];self::assertTransition($d,$target,$comment);$beforeIncident=$target==='Incident'?$from:($from==='Incident'&&$target!== 'Annulée'?null:$d['status_before_incident']);$fields='status=:status,status_before_incident=:before_incident,updated_by=:user';$params=['status'=>$target,'before_incident'=>$beforeIncident,'user'=>Auth::id(),'id'=>$id];if($target==='Livrée'){$fields.=',delivered_at=NOW()';}if($target==='Clôturée'){$fields.=',closed_at=NOW()';}if($target==='Annulée'){$fields.=',cancellation_reason=:reason';$params['reason']=$comment;}$pdo->prepare('UPDATE deliveries SET '.$fields.' WHERE id=:id')->execute($params);self::logStatus($pdo,$id,$from,$target,$comment);self::syncResources($pdo,$id,$target,$d);self::syncOperationalHistory($pdo,$d,$target);$pdo->commit();return ['from'=>$from,'to'=>$target];}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function allowedNext(array $delivery): array
    {
        $current=$delivery['status'];if(in_array($current,['Clôturée','Annulée'],true)){return [];}if($current==='Incident'){return array_values(array_filter([$delivery['status_before_incident']??null,'Annulée']));}$index=array_search($current,self::FLOW,true);$next=$index!==false&&isset(self::FLOW[$index+1])?[self::FLOW[$index+1]]:[];$next=array_values(array_filter($next,function($status){return $status!=='Livrée';}));if(!in_array($current,['Livrée','Clôturée'],true)){$next[]='Annulée';}return array_values(array_unique($next));
    }

    private static function assertTransition(array $d,string $target,?string $comment): void{if($target==='Incident'){throw new RuntimeException('Utilisez le formulaire de signalement afin de documenter complètement l’incident.');}if(!in_array($target,self::allowedNext($d),true)){throw new RuntimeException('Transition de statut non autorisée.');}if($target==='Livrée'){throw new RuntimeException('La livraison doit être confirmée par le chauffeur avec une preuve numérique.');}if($target==='Annulée'&&trim((string)$comment)===''){throw new RuntimeException('Un commentaire est obligatoire pour ce statut.');}if(in_array($target,['À préparer','Prête','Chargement','Chargée','Partie','En transit','Arrivée'],true)&&(!$d['driver_id']||!$d['vehicle_id'])){throw new RuntimeException('Un chauffeur et un véhicule doivent être affectés.');}}
    private static function assertRelations(PDO $pdo,array $d): void{$s=$pdo->prepare("SELECT COUNT(*) FROM clients WHERE id=:id AND status<>'archived'");$s->execute(['id'=>(int)$d['client_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Client invalide.');}$s=$pdo->prepare("SELECT COUNT(*) FROM client_sites WHERE id=:site AND client_id=:client AND status='active'");$s->execute(['site'=>(int)$d['client_site_id'],'client'=>(int)$d['client_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Le site ne correspond pas au client.');}if(!empty($d['client_contact_id'])){$s=$pdo->prepare('SELECT COUNT(*) FROM client_contacts WHERE id=:contact AND client_id=:client');$s->execute(['contact'=>(int)$d['client_contact_id'],'client'=>(int)$d['client_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Le contact ne correspond pas au client.');}}if(!empty($d['driver_id'])){$s=$pdo->prepare('SELECT COUNT(*) FROM drivers WHERE id=:id AND is_active=1');$s->execute(['id'=>(int)$d['driver_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Chauffeur invalide.');}}if(!empty($d['vehicle_id'])){$s=$pdo->prepare('SELECT COUNT(*) FROM vehicles WHERE id=:id AND is_active=1');$s->execute(['id'=>(int)$d['vehicle_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Véhicule invalide.');}}}
    private static function replaceGoods(PDO $pdo,int $id,array $rows): void{if($rows===[]){throw new RuntimeException('Ajoutez au moins une marchandise.');}$pdo->prepare('DELETE FROM delivery_goods WHERE delivery_id=:id')->execute(['id'=>$id]);$insert=$pdo->prepare('INSERT INTO delivery_goods (delivery_id,goods_id,quantity,unit,unit_weight_kg,description_snapshot) VALUES (:delivery_id,NULL,:quantity,:unit,:unit_weight_kg,:description)');foreach($rows as $row){$description=trim((string)($row['description']??''));$quantity=(float)($row['quantity']??0);$unit=trim((string)($row['unit']??''));$weight=$row['unit_weight_kg']??'';if(mb_strlen($description)<2||mb_strlen($description)>255||$quantity<=0||$unit===''||mb_strlen($unit)>30||($weight!==''&&(!is_numeric($weight)||(float)$weight<=0))){throw new RuntimeException('Une ligne de marchandise est invalide.');}$insert->execute(['delivery_id'=>$id,'quantity'=>$quantity,'unit'=>$unit,'unit_weight_kg'=>$weight===''?null:(float)$weight,'description'=>$description]);}}
    private static function params(array $d): array{return ['client_id'=>(int)$d['client_id'],'client_site_id'=>(int)$d['client_site_id'],'client_contact_id'=>!empty($d['client_contact_id'])?(int)$d['client_contact_id']:null,'scheduled_at'=>str_replace('T',' ',trim((string)$d['scheduled_at'])),'priority'=>$d['priority']??'Normale','driver_id'=>!empty($d['driver_id'])?(int)$d['driver_id']:null,'vehicle_id'=>!empty($d['vehicle_id'])?(int)$d['vehicle_id']:null,'observations'=>trim((string)($d['observations']??''))?:null];}
    private static function nextReference(PDO $pdo): string{$year=(int)date('Y');$pdo->prepare('INSERT IGNORE INTO delivery_sequences (sequence_year,current_value) VALUES (:year,0)')->execute(['year'=>$year]);$s=$pdo->prepare('SELECT current_value FROM delivery_sequences WHERE sequence_year=:year FOR UPDATE');$s->execute(['year'=>$year]);$next=(int)$s->fetchColumn()+1;$pdo->prepare('UPDATE delivery_sequences SET current_value=:value WHERE sequence_year=:year')->execute(['value'=>$next,'year'=>$year]);return 'DLV-'.$year.'-'.str_pad((string)$next,5,'0',STR_PAD_LEFT);}
    private static function logStatus(PDO $pdo,int $id,?string $from,string $to,?string $comment): void{$s=$pdo->prepare('INSERT INTO delivery_status_history (delivery_id,from_status,to_status,comment,changed_by) VALUES (:id,:from_status,:to_status,:comment,:user)');$s->execute(['id'=>$id,'from_status'=>$from,'to_status'=>$to,'comment'=>$comment,'user'=>Auth::id()]);}
    private static function syncResources(PDO $pdo,int $id,string $status,array $data): void{$driver=$data['driver_id']??null;$vehicle=$data['vehicle_id']??null;if(!$driver&&!$vehicle){return;}$resourceStatus=in_array($status,['Partie','En transit','Arrivée'],true)?['En mission','En livraison']:(in_array($status,['Livrée','Clôturée','Annulée'],true)?['Disponible','Disponible']:['Affecté','Affecté']);if($status==='Incident'){$resourceStatus=['Indisponible','Indisponible'];}if($driver){$pdo->prepare('UPDATE drivers SET status=:status,updated_by=:user WHERE id=:id')->execute(['status'=>$resourceStatus[0],'user'=>Auth::id(),'id'=>$driver]);}if($vehicle){$pdo->prepare('UPDATE vehicles SET status=:status,assigned_driver_id=:driver,updated_by=:user WHERE id=:id')->execute(['status'=>$resourceStatus[1],'driver'=>in_array($status,['Livrée','Clôturée','Annulée'],true)?null:$driver,'user'=>Auth::id(),'id'=>$vehicle]);}}
    private static function syncOperationalHistory(PDO $pdo,array $d,string $status): void{if(!$d['vehicle_id']&&!$d['driver_id']){return;}if($status==='Partie'){if($d['vehicle_id']){$s=$pdo->prepare('INSERT INTO vehicle_delivery_history (vehicle_id,delivery_reference,client_name,origin,destination,driver_name,started_at,status) SELECT :vehicle,:reference,c.company_name,s.city,s.name,CONCAT(dr.first_name," ",dr.last_name),NOW(),"En transit" FROM clients c JOIN client_sites s ON s.id=:site LEFT JOIN drivers dr ON dr.id=:driver WHERE c.id=:client');$s->execute(['vehicle'=>$d['vehicle_id'],'reference'=>$d['reference'],'site'=>$d['client_site_id'],'driver'=>$d['driver_id'],'client'=>$d['client_id']]);}if($d['driver_id']){$s=$pdo->prepare('INSERT INTO driver_missions (driver_id,mission_reference,origin,destination,started_at,status) SELECT :driver,:reference,c.city,s.city,NOW(),"En mission" FROM clients c JOIN client_sites s ON s.id=:site WHERE c.id=:client');$s->execute(['driver'=>$d['driver_id'],'reference'=>$d['reference'],'site'=>$d['client_site_id'],'client'=>$d['client_id']]);}}if(in_array($status,['Livrée','Clôturée','Annulée'],true)){$pdo->prepare('UPDATE vehicle_delivery_history SET completed_at=NOW(),status=:status WHERE delivery_reference=:reference')->execute(['status'=>$status==='Annulée'?'Annulée':'Livrée','reference'=>$d['reference']]);$pdo->prepare('UPDATE driver_missions SET completed_at=NOW(),status=:status WHERE mission_reference=:reference')->execute(['status'=>$status==='Annulée'?'Annulée':'Terminée','reference'=>$d['reference']]);}}
}
