<?php

declare(strict_types=1);

namespace App\Models;

use App\Core\Auth;
use App\Core\Database;
use PDO;
use RuntimeException;
use Throwable;

final class Delivery
{
    public const FLOW=['Brouillon','Affectée','À préparer','Prête','Chargement','Chargée','Partie','En transit','Arrivée','Livrée','Clôturée'];
    public const EXCEPTIONS=['Incident','Annulée'];

    public static function listing(array $filters): array
    {
        $where=['1=1'];$params=[];if(($filters['status']??'')!==''){$where[]='d.status=:status';$params['status']=$filters['status'];}if(($filters['priority']??'')!==''){$where[]='d.priority=:priority';$params['priority']=$filters['priority'];}if(($filters['client_id']??'')!==''){$where[]='d.client_id=:client';$params['client']=(int)$filters['client_id'];}if(($filters['date_from']??'')!==''){$where[]='DATE(d.scheduled_at)>=:date_from';$params['date_from']=$filters['date_from'];}if(($filters['date_to']??'')!==''){$where[]='DATE(d.scheduled_at)<=:date_to';$params['date_to']=$filters['date_to'];}if(($filters['search']??'')!==''){$term='%'.$filters['search'].'%';$where[]='(d.reference LIKE :s1 OR c.company_name LIKE :s2 OR fd.label LIKE :s3 OR CONCAT(dr.first_name," ",dr.last_name) LIKE :s4 OR v.registration_number LIKE :s5)';foreach(['s1','s2','s3','s4','s5'] as $key){$params[$key]=$term;}}
        $sql='SELECT d.id,d.reference,d.scheduled_at,d.priority,d.status,d.updated_at,c.company_name,COALESCE(fd.label,"Destination") site_name,COALESCE(fd.city,"") city,dr.first_name driver_first_name,dr.last_name driver_last_name,v.registration_number,COUNT(DISTINCT dg.id) goods_count,COALESCE(SUM(dg.quantity*COALESCE(dg.unit_weight_kg,0)),0) total_weight_kg,EXISTS(SELECT 1 FROM delivery_pods pod WHERE pod.delivery_id=d.id) has_pod,(SELECT COUNT(*) FROM delivery_destinations dc WHERE dc.delivery_id=d.id) destination_count FROM deliveries d JOIN clients c ON c.id=d.client_id LEFT JOIN delivery_destinations fd ON fd.id=(SELECT dx.id FROM delivery_destinations dx WHERE dx.delivery_id=d.id ORDER BY dx.stop_order LIMIT 1) LEFT JOIN drivers dr ON dr.id=d.driver_id LEFT JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN delivery_goods dg ON dg.delivery_id=d.id WHERE '.implode(' AND ',$where).' GROUP BY d.id ORDER BY d.scheduled_at DESC,d.id DESC';$statement=Database::connection()->prepare($sql);$statement->execute($params);return $statement->fetchAll();
    }

    public static function find(int $id): ?array
    {
        $sql='SELECT d.*,c.company_name,c.code client_code,COALESCE(fd.label,"Destination") site_name,COALESCE(fd.address_line,"") site_address,COALESCE(fd.city,"") site_city,fd.latitude site_latitude,fd.longitude site_longitude,fd.instructions delivery_instructions,fd.contact_name,fd.contact_phone,NULL contact_email,dr.first_name driver_first_name,dr.last_name driver_last_name,dr.phone driver_phone,v.registration_number,v.brand vehicle_brand,v.model vehicle_model,u.name creator_name FROM deliveries d JOIN clients c ON c.id=d.client_id LEFT JOIN delivery_destinations fd ON fd.id=(SELECT dx.id FROM delivery_destinations dx WHERE dx.delivery_id=d.id ORDER BY dx.stop_order LIMIT 1) LEFT JOIN drivers dr ON dr.id=d.driver_id LEFT JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN users u ON u.id=d.created_by WHERE d.id=:id';$s=Database::connection()->prepare($sql);$s->execute(['id'=>$id]);$d=$s->fetch();if(!$d){return null;}$g=Database::connection()->prepare('SELECT dg.*,g.reference,dd.stop_order destination_order,dd.label destination_label FROM delivery_goods dg LEFT JOIN goods g ON g.id=dg.goods_id LEFT JOIN delivery_destinations dd ON dd.id=dg.destination_id WHERE dg.delivery_id=:id ORDER BY COALESCE(dd.stop_order,999),dg.id');$g->execute(['id'=>$id]);$d['goods']=$g->fetchAll();$dest=Database::connection()->prepare('SELECT dd.*,p.id pod_id,p.recipient_name,p.captured_at pod_captured_at FROM delivery_destinations dd LEFT JOIN delivery_pods p ON p.destination_id=dd.id WHERE dd.delivery_id=:id ORDER BY dd.stop_order');$dest->execute(['id'=>$id]);$d['destinations']=$dest->fetchAll();$h=Database::connection()->prepare('SELECT h.*,u.name user_name FROM delivery_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.delivery_id=:id ORDER BY h.changed_at,h.id');$h->execute(['id'=>$id]);$d['timeline']=$h->fetchAll();$d['pods']=DeliveryPod::summaries($id);$d['pod']=$d['pods'][0]??null;return $d;
    }

    public static function clients(): array{return Database::connection()->query("SELECT id,code,company_name FROM clients WHERE status IN ('active','prospect') ORDER BY company_name")->fetchAll();}
    public static function goodsCatalog(): array{return Database::connection()->query("SELECT id,reference,designation,unit,unit_weight_kg FROM goods WHERE status='Actif' ORDER BY designation")->fetchAll();}
    public static function drivers(): array{return Database::connection()->query("SELECT id,first_name,last_name,status FROM drivers WHERE is_active=1 ORDER BY last_name,first_name")->fetchAll();}
    public static function vehicles(): array{return Database::connection()->query("SELECT id,registration_number,brand,model,status,assigned_driver_id FROM vehicles WHERE is_active=1 ORDER BY registration_number")->fetchAll();}
    public static function clientOptions(int $clientId): array{$sites=Database::connection()->prepare("SELECT id,name,address_line1,city,latitude,longitude,is_default FROM client_sites WHERE client_id=:id AND status='active' ORDER BY is_default DESC,name");$sites->execute(['id'=>$clientId]);$contacts=Database::connection()->prepare('SELECT id,full_name,job_title,email,phone,is_primary FROM client_contacts WHERE client_id=:id ORDER BY is_primary DESC,full_name');$contacts->execute(['id'=>$clientId]);return ['sites'=>$sites->fetchAll(),'contacts'=>$contacts->fetchAll()];}

    public static function create(array $data): int
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{self::assertRelations($pdo,$data);$reference=self::nextReference($pdo);$p=self::params($data);$p['reference']=$reference;$p['created_by']=Auth::id();$p['updated_by']=Auth::id();$p['status']=$p['driver_id']&&$p['vehicle_id']?'Affectée':'Brouillon';$sql='INSERT INTO deliveries (reference,client_id,client_site_id,client_contact_id,scheduled_at,priority,driver_id,vehicle_id,status,observations,created_by,updated_by) VALUES (:reference,:client_id,NULL,NULL,:scheduled_at,:priority,:driver_id,:vehicle_id,:status,:observations,:created_by,:updated_by)';$pdo->prepare($sql)->execute($p);$id=(int)$pdo->lastInsertId();$destinationIds=self::replaceDestinations($pdo,$id,$data['destinations']??[]);self::replaceGoods($pdo,$id,$data['goods']??[],$destinationIds);self::logStatus($pdo,$id,null,$p['status'],$p['status']==='Affectée'?'Livraison créée et transmise au chauffeur':'Livraison créée avec '.count($destinationIds).' destination(s)');self::syncResources($pdo,$id,$p['status'],$data);$pdo->commit();return $id;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function update(int $id,array $data): bool
    {
        $old=self::find($id);if(!$old){return false;}if(!in_array($old['status'],['Brouillon','À préparer','Prête','Chargement','Chargée'],true)){throw new RuntimeException('Cette livraison ne peut plus être modifiée après son départ.');}$pdo=Database::connection();$pdo->beginTransaction();try{self::assertRelations($pdo,$data);$p=self::params($data);$p['id']=$id;$p['updated_by']=Auth::id();$sql='UPDATE deliveries SET client_id=:client_id,client_site_id=NULL,client_contact_id=NULL,scheduled_at=:scheduled_at,priority=:priority,driver_id=:driver_id,vehicle_id=:vehicle_id,observations=:observations,updated_by=:updated_by WHERE id=:id';$pdo->prepare($sql)->execute($p);$destinationIds=self::replaceDestinations($pdo,$id,$data['destinations']??[]);self::replaceGoods($pdo,$id,$data['goods']??[],$destinationIds);if($old['driver_id']&&(int)$old['driver_id']!==(int)($data['driver_id']??0)){$pdo->prepare("UPDATE drivers SET status='Disponible',updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$old['driver_id']]);}if($old['vehicle_id']&&(int)$old['vehicle_id']!==(int)($data['vehicle_id']??0)){$pdo->prepare("UPDATE vehicles SET status='Disponible',assigned_driver_id=NULL,updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$old['vehicle_id']]);}self::syncResources($pdo,$id,$old['status'],$data);$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function delete(int $id): bool
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$statement=$pdo->prepare('SELECT id,driver_id,vehicle_id FROM deliveries WHERE id=:id FOR UPDATE');$statement->execute(['id'=>$id]);$delivery=$statement->fetch();if(!$delivery){$pdo->rollBack();return false;}$pdo->prepare('DELETE FROM deliveries WHERE id=:id')->execute(['id'=>$id]);if($delivery['driver_id']){self::releaseDriverIfUnused($pdo,(int)$delivery['driver_id']);}if($delivery['vehicle_id']){self::releaseVehicleIfUnused($pdo,(int)$delivery['vehicle_id']);}$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function transition(int $id,string $target,?string $comment): array
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM deliveries WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$d=$s->fetch();if(!$d){throw new RuntimeException('Livraison introuvable.');}$from=$d['status'];self::assertTransition($d,$target,$comment);$beforeIncident=$target==='Incident'?$from:($from==='Incident'&&$target!== 'Annulée'?null:$d['status_before_incident']);$fields='status=:status,status_before_incident=:before_incident,updated_by=:user';$params=['status'=>$target,'before_incident'=>$beforeIncident,'user'=>Auth::id(),'id'=>$id];if($target==='Livrée'){$fields.=',delivered_at=NOW()';}if($target==='Clôturée'){$fields.=',closed_at=NOW()';}if($target==='Annulée'){$fields.=',cancellation_reason=:reason';$params['reason']=$comment;}$pdo->prepare('UPDATE deliveries SET '.$fields.' WHERE id=:id')->execute($params);self::logStatus($pdo,$id,$from,$target,$comment);self::syncResources($pdo,$id,$target,$d);self::syncOperationalHistory($pdo,$d,$target);$pdo->commit();return ['from'=>$from,'to'=>$target];}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}
    }

    public static function allowedNext(array $delivery): array
    {
        $current=$delivery['status'];if(in_array($current,['Clôturée','Annulée'],true)){return [];}if($current==='Incident'){return array_values(array_filter([$delivery['status_before_incident']??null,'Annulée']));}$index=array_search($current,self::FLOW,true);$next=$index!==false&&isset(self::FLOW[$index+1])?[self::FLOW[$index+1]]:[];$next=array_values(array_filter($next,function($status){return $status!=='Livrée';}));if(!in_array($current,['Livrée','Clôturée'],true)){$next[]='Annulée';}return array_values(array_unique($next));
    }

    private static function assertTransition(array $d,string $target,?string $comment): void{if($target==='Incident'){throw new RuntimeException('Utilisez le formulaire de signalement afin de documenter complètement l’incident.');}if(!in_array($target,self::allowedNext($d),true)){throw new RuntimeException('Transition de statut non autorisée.');}if($target==='Livrée'){throw new RuntimeException('La livraison doit être confirmée par le chauffeur avec une preuve numérique.');}if($target==='Annulée'&&trim((string)$comment)===''){throw new RuntimeException('Un commentaire est obligatoire pour ce statut.');}if(in_array($target,['Affectée','À préparer','Prête','Chargement','Chargée','Partie','En transit','Arrivée'],true)&&(!$d['driver_id']||!$d['vehicle_id'])){throw new RuntimeException('Un chauffeur et un véhicule doivent être affectés.');}}
    private static function assertRelations(PDO $pdo,array $d): void{if(empty($d['driver_id'])!==empty($d['vehicle_id'])){throw new RuntimeException('Le chauffeur et le véhicule doivent être affectés ensemble.');}$s=$pdo->prepare("SELECT COUNT(*) FROM clients WHERE id=:id AND status<>'archived'");$s->execute(['id'=>(int)$d['client_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Client invalide.');}if(!empty($d['driver_id'])){$s=$pdo->prepare('SELECT COUNT(*) FROM drivers WHERE id=:id AND is_active=1');$s->execute(['id'=>(int)$d['driver_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Chauffeur invalide.');}}if(!empty($d['vehicle_id'])){$s=$pdo->prepare('SELECT COUNT(*) FROM vehicles WHERE id=:id AND is_active=1');$s->execute(['id'=>(int)$d['vehicle_id']]);if(!(int)$s->fetchColumn()){throw new RuntimeException('Véhicule invalide.');}}}
    private static function replaceDestinations(PDO $pdo,int $id,array $rows): array{if($rows===[]){throw new RuntimeException('Ajoutez au moins une destination.');}$pdo->prepare('DELETE FROM delivery_destinations WHERE delivery_id=:id')->execute(['id'=>$id]);$insert=$pdo->prepare('INSERT INTO delivery_destinations (delivery_id,stop_order,label,address_line,city,contact_name,contact_phone,instructions,latitude,longitude) VALUES (:delivery,:position,:label,:address,:city,:contact,:phone,:instructions,:latitude,:longitude)');$ids=[];foreach(array_values($rows) as $i=>$row){$label=trim((string)($row['label']??''));$address=trim((string)($row['address']??''));if(mb_strlen($label)<2||mb_strlen($label)>160||mb_strlen($address)<3||mb_strlen($address)>255){throw new RuntimeException('Une destination est invalide.');}$lat=trim((string)($row['latitude']??''));$lng=trim((string)($row['longitude']??''));if(($lat!==''&&(!is_numeric($lat)||(float)$lat < -90||(float)$lat > 90))||($lng!==''&&(!is_numeric($lng)||(float)$lng < -180||(float)$lng > 180))){throw new RuntimeException('Les coordonnées d’une destination sont invalides.');}$insert->execute(['delivery'=>$id,'position'=>$i+1,'label'=>$label,'address'=>$address,'city'=>trim((string)($row['city']??''))?:null,'contact'=>trim((string)($row['contact_name']??''))?:null,'phone'=>trim((string)($row['contact_phone']??''))?:null,'instructions'=>trim((string)($row['instructions']??''))?:null,'latitude'=>$lat===''?null:(float)$lat,'longitude'=>$lng===''?null:(float)$lng]);$ids[$i]=(int)$pdo->lastInsertId();}return $ids;}
    private static function replaceGoods(PDO $pdo,int $id,array $rows,array $destinationIds): void
    {
        if($rows===[]){throw new RuntimeException('Ajoutez au moins une marchandise à chaque destination.');}$pdo->prepare('DELETE FROM delivery_goods WHERE delivery_id=:id')->execute(['id'=>$id]);$insert=$pdo->prepare('INSERT INTO delivery_goods (delivery_id,destination_id,goods_id,quantity,unit,unit_weight_kg,description_snapshot) VALUES (:delivery_id,:destination_id,NULL,:quantity,:unit,:unit_weight_kg,:description)');$counts=array_fill_keys(array_keys($destinationIds),0);
        foreach($rows as $row){$description=trim((string)($row['description']??''));$quantity=(float)($row['quantity']??0);$unit=trim((string)($row['unit']??''));$weight=$row['unit_weight_kg']??'';$destinationIndex=(int)($row['destination_index']??0);if(!isset($destinationIds[$destinationIndex])||mb_strlen($description)<2||mb_strlen($description)>255||$quantity<=0||$unit===''||mb_strlen($unit)>30||($weight!==''&&(!is_numeric($weight)||(float)$weight<=0))){throw new RuntimeException('Une ligne de marchandise est invalide ou sans destination.');}$insert->execute(['delivery_id'=>$id,'destination_id'=>$destinationIds[$destinationIndex],'quantity'=>$quantity,'unit'=>$unit,'unit_weight_kg'=>$weight===''?null:(float)$weight,'description'=>$description]);$counts[$destinationIndex]++;}
        foreach($counts as $destinationIndex=>$count){if($count===0){throw new RuntimeException('La destination '.($destinationIndex+1).' doit contenir au moins une marchandise.');}}
    }
    private static function params(array $d): array{return ['client_id'=>(int)$d['client_id'],'scheduled_at'=>str_replace('T',' ',trim((string)$d['scheduled_at'])),'priority'=>$d['priority']??'Normale','driver_id'=>!empty($d['driver_id'])?(int)$d['driver_id']:null,'vehicle_id'=>!empty($d['vehicle_id'])?(int)$d['vehicle_id']:null,'observations'=>trim((string)($d['observations']??''))?:null];}
    private static function nextReference(PDO $pdo): string{$year=(int)date('Y');$pdo->prepare('INSERT IGNORE INTO delivery_sequences (sequence_year,current_value) VALUES (:year,0)')->execute(['year'=>$year]);$s=$pdo->prepare('SELECT current_value FROM delivery_sequences WHERE sequence_year=:year FOR UPDATE');$s->execute(['year'=>$year]);$next=(int)$s->fetchColumn()+1;$pdo->prepare('UPDATE delivery_sequences SET current_value=:value WHERE sequence_year=:year')->execute(['value'=>$next,'year'=>$year]);return 'DLV-'.$year.'-'.str_pad((string)$next,5,'0',STR_PAD_LEFT);}
    private static function releaseDriverIfUnused(PDO $pdo,int $driverId): void{$s=$pdo->prepare("SELECT COUNT(*) FROM deliveries WHERE driver_id=:id AND status NOT IN ('Livrée','Clôturée','Annulée')");$s->execute(['id'=>$driverId]);if((int)$s->fetchColumn()===0){$pdo->prepare("UPDATE drivers SET status='Disponible',updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$driverId]);}}
    private static function releaseVehicleIfUnused(PDO $pdo,int $vehicleId): void{$s=$pdo->prepare("SELECT COUNT(*) FROM deliveries WHERE vehicle_id=:id AND status NOT IN ('Livrée','Clôturée','Annulée')");$s->execute(['id'=>$vehicleId]);if((int)$s->fetchColumn()===0){$pdo->prepare("UPDATE vehicles SET status='Disponible',assigned_driver_id=NULL,updated_by=:user WHERE id=:id")->execute(['user'=>Auth::id(),'id'=>$vehicleId]);}}
    private static function logStatus(PDO $pdo,int $id,?string $from,string $to,?string $comment): void{$s=$pdo->prepare('INSERT INTO delivery_status_history (delivery_id,from_status,to_status,comment,changed_by) VALUES (:id,:from_status,:to_status,:comment,:user)');$s->execute(['id'=>$id,'from_status'=>$from,'to_status'=>$to,'comment'=>$comment,'user'=>Auth::id()]);}
    private static function syncResources(PDO $pdo,int $id,string $status,array $data): void{$driver=$data['driver_id']??null;$vehicle=$data['vehicle_id']??null;if(!$driver&&!$vehicle){return;}$resourceStatus=in_array($status,['Partie','En transit','Arrivée'],true)?['En mission','En livraison']:(in_array($status,['Livrée','Clôturée','Annulée'],true)?['Disponible','Disponible']:['Affecté','Affecté']);if($status==='Incident'){$resourceStatus=['Indisponible','Indisponible'];}if($driver){$pdo->prepare('UPDATE drivers SET status=:status,updated_by=:user WHERE id=:id')->execute(['status'=>$resourceStatus[0],'user'=>Auth::id(),'id'=>$driver]);}if($vehicle){$pdo->prepare('UPDATE vehicles SET status=:status,assigned_driver_id=:driver,updated_by=:user WHERE id=:id')->execute(['status'=>$resourceStatus[1],'driver'=>in_array($status,['Livrée','Clôturée','Annulée'],true)?null:$driver,'user'=>Auth::id(),'id'=>$vehicle]);}}
    private static function syncOperationalHistory(PDO $pdo,array $d,string $status): void{if(!$d['vehicle_id']&&!$d['driver_id']){return;}if($status==='Partie'){$destination=$pdo->prepare('SELECT label,city FROM delivery_destinations WHERE delivery_id=:id ORDER BY stop_order DESC LIMIT 1');$destination->execute(['id'=>$d['id']]);$last=$destination->fetch()?:['label'=>'Destination','city'=>''];$client=$pdo->prepare('SELECT company_name,city FROM clients WHERE id=:id');$client->execute(['id'=>$d['client_id']]);$customer=$client->fetch()?:['company_name'=>'Client','city'=>''];if($d['vehicle_id']){$s=$pdo->prepare('INSERT INTO vehicle_delivery_history (vehicle_id,delivery_reference,client_name,origin,destination,driver_name,started_at,status) SELECT :vehicle,:reference,:client,:origin,:destination,CONCAT(dr.first_name," ",dr.last_name),NOW(),"En transit" FROM drivers dr WHERE dr.id=:driver');$s->execute(['vehicle'=>$d['vehicle_id'],'reference'=>$d['reference'],'client'=>$customer['company_name'],'origin'=>$customer['city']??'','destination'=>$last['label'],'driver'=>$d['driver_id']]);}if($d['driver_id']){$s=$pdo->prepare('INSERT INTO driver_missions (driver_id,mission_reference,origin,destination,started_at,status) VALUES (:driver,:reference,:origin,:destination,NOW(),"En mission")');$s->execute(['driver'=>$d['driver_id'],'reference'=>$d['reference'],'origin'=>$customer['city']??'','destination'=>$last['city']?:$last['label']]);}}if(in_array($status,['Livrée','Clôturée','Annulée'],true)){$pdo->prepare('UPDATE vehicle_delivery_history SET completed_at=NOW(),status=:status WHERE delivery_reference=:reference')->execute(['status'=>$status==='Annulée'?'Annulée':'Livrée','reference'=>$d['reference']]);$pdo->prepare('UPDATE driver_missions SET completed_at=NOW(),status=:status WHERE mission_reference=:reference')->execute(['status'=>$status==='Annulée'?'Annulée':'Terminée','reference'=>$d['reference']]);}}
}
