<?php

declare(strict_types=1);

namespace App\Models;

use App\Core\Auth;
use App\Core\Database;
use PDO;
use Throwable;

final class Vehicle
{
    public static function listing(array $filters): array
    {
        $where=['1=1'];$params=[];if(($filters['status']??'')!==''){$where[]='v.status=:status';$params['status']=$filters['status'];}if(($filters['type']??'')!==''){$where[]='v.vehicle_type=:type';$params['type']=$filters['type'];}if(($filters['active']??'1')!=='all'){$where[]='v.is_active=:active';$params['active']=(int)$filters['active'];}if(($filters['expiry']??'')==='soon'){$where[]='EXISTS(SELECT 1 FROM vehicle_documents dx WHERE dx.vehicle_id=v.id AND dx.expires_at BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 60 DAY))';}elseif(($filters['expiry']??'')==='expired'){$where[]='EXISTS(SELECT 1 FROM vehicle_documents dx WHERE dx.vehicle_id=v.id AND dx.expires_at<CURDATE())';}if(($filters['search']??'')!==''){$term='%'.$filters['search'].'%';$where[]='(v.registration_number LIKE :s1 OR v.brand LIKE :s2 OR v.model LIKE :s3 OR v.code LIKE :s4)';foreach(['s1','s2','s3','s4'] as $k){$params[$k]=$term;}}
        $sql='SELECT v.id,v.code,v.registration_number,v.brand,v.model,v.vehicle_type,v.capacity_value,v.capacity_unit,v.status,v.is_active,v.mileage_km,v.updated_at,d.first_name driver_first_name,d.last_name driver_last_name,(SELECT MIN(expires_at) FROM vehicle_documents vd WHERE vd.vehicle_id=v.id AND vd.expires_at IS NOT NULL) next_expiry,(SELECT COUNT(*) FROM vehicle_documents vd WHERE vd.vehicle_id=v.id) documents_count,(SELECT COUNT(*) FROM vehicle_delivery_history vh WHERE vh.vehicle_id=v.id) deliveries_count FROM vehicles v LEFT JOIN drivers d ON d.id=v.assigned_driver_id WHERE '.implode(' AND ',$where).' ORDER BY v.registration_number';$s=Database::connection()->prepare($sql);$s->execute($params);return $s->fetchAll();
    }
    public static function types(): array{return Database::connection()->query("SELECT DISTINCT vehicle_type FROM vehicles WHERE vehicle_type<>'' ORDER BY vehicle_type")->fetchAll(PDO::FETCH_COLUMN);}
    public static function availableDrivers(): array{return Database::connection()->query("SELECT id,first_name,last_name,status FROM drivers WHERE is_active=1 ORDER BY last_name,first_name")->fetchAll();}
    public static function find(int $id): ?array
    {
        $s=Database::connection()->prepare('SELECT v.*,d.first_name driver_first_name,d.last_name driver_last_name,d.phone driver_phone,uc.name creator_name FROM vehicles v LEFT JOIN drivers d ON d.id=v.assigned_driver_id LEFT JOIN users uc ON uc.id=v.created_by WHERE v.id=:id');$s->execute(['id'=>$id]);$v=$s->fetch();if(!$v){return null;}$docs=Database::connection()->prepare('SELECT id,vehicle_id,document_type,document_number,issued_at,expires_at,file_name,file_mime,file_size,created_at FROM vehicle_documents WHERE vehicle_id=:id ORDER BY COALESCE(expires_at,"9999-12-31"),id');$docs->execute(['id'=>$id]);$v['documents']=$docs->fetchAll();$del=Database::connection()->prepare('SELECT * FROM vehicle_delivery_history WHERE vehicle_id=:id ORDER BY COALESCE(started_at,created_at) DESC,id DESC');$del->execute(['id'=>$id]);$v['deliveries']=$del->fetchAll();$h=Database::connection()->prepare('SELECT h.*,u.name user_name FROM vehicle_history h LEFT JOIN users u ON u.id=h.user_id WHERE h.vehicle_id=:id ORDER BY h.created_at DESC,h.id DESC');$h->execute(['id'=>$id]);$v['history']=$h->fetchAll();return $v;
    }
    public static function create(array $data): int{$pdo=Database::connection();$pdo->beginTransaction();try{$p=self::params($data);$p['code']=self::nextCode($pdo);$p['created_by']=Auth::id();$p['updated_by']=Auth::id();$sql='INSERT INTO vehicles (code,registration_number,brand,model,vehicle_type,manufacture_year,color,capacity_value,capacity_unit,mileage_km,status,assigned_driver_id,available_from,notes,is_active,created_by,updated_by) VALUES (:code,:registration_number,:brand,:model,:vehicle_type,:manufacture_year,:color,:capacity_value,:capacity_unit,:mileage_km,:status,:assigned_driver_id,:available_from,:notes,1,:created_by,:updated_by)';$pdo->prepare($sql)->execute($p);$id=(int)$pdo->lastInsertId();self::history($pdo,$id,'created','Véhicule créé',['code'=>$p['code']]);$pdo->commit();return $id;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}}
    public static function update(int $id,array $data): bool{$old=self::find($id);if(!$old){return false;}$pdo=Database::connection();$pdo->beginTransaction();try{$p=self::params($data);$p['id']=$id;$p['updated_by']=Auth::id();$sql='UPDATE vehicles SET registration_number=:registration_number,brand=:brand,model=:model,vehicle_type=:vehicle_type,manufacture_year=:manufacture_year,color=:color,capacity_value=:capacity_value,capacity_unit=:capacity_unit,mileage_km=:mileage_km,status=:status,assigned_driver_id=:assigned_driver_id,available_from=:available_from,notes=:notes,updated_by=:updated_by WHERE id=:id';$pdo->prepare($sql)->execute($p);self::history($pdo,$id,'updated','Fiche véhicule mise à jour',['status'=>[$old['status'],$data['status']??''],'driver'=>[$old['assigned_driver_id'],$data['assigned_driver_id']??null]]);$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}}
    public static function deactivate(int $id): bool{$pdo=Database::connection();$s=$pdo->prepare("UPDATE vehicles SET is_active=0,status='Indisponible',assigned_driver_id=NULL,updated_by=:user WHERE id=:id AND is_active=1");$s->execute(['id'=>$id,'user'=>Auth::id()]);if($s->rowCount()){self::history($pdo,$id,'deactivated','Véhicule désactivé',null);return true;}return false;}
    public static function addDocument(int $id,array $meta,array $file): int{$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO vehicle_documents (vehicle_id,document_type,document_number,issued_at,expires_at,file_name,file_mime,file_data,file_size,uploaded_by) SELECT :vehicle_id,:document_type,:document_number,:issued_at,:expires_at,:file_name,:file_mime,:file_data,:file_size,:user FROM vehicles WHERE id=:vehicle_check');$s->execute(['vehicle_id'=>$id,'document_type'=>$meta['document_type'],'document_number'=>self::nullable($meta['document_number']??null),'issued_at'=>self::nullable($meta['issued_at']??null),'expires_at'=>self::nullable($meta['expires_at']??null),'file_name'=>$file['name'],'file_mime'=>$file['mime'],'file_data'=>$file['data'],'file_size'=>$file['size'],'user'=>Auth::id(),'vehicle_check'=>$id]);if(!$s->rowCount()){throw new \RuntimeException('Véhicule introuvable.');}$documentId=(int)$pdo->lastInsertId();self::history($pdo,$id,'document_added','Document ajouté : '.$meta['document_type'],['document_id'=>$documentId]);$pdo->commit();return $documentId;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}}
    public static function document(int $vehicleId,int $documentId): ?array{$s=Database::connection()->prepare('SELECT file_name,file_mime,file_data FROM vehicle_documents WHERE id=:document AND vehicle_id=:vehicle');$s->execute(['document'=>$documentId,'vehicle'=>$vehicleId]);$d=$s->fetch();return $d?:null;}
    public static function deleteDocument(int $vehicleId,int $documentId): bool{$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT document_type FROM vehicle_documents WHERE id=:document AND vehicle_id=:vehicle');$s->execute(['document'=>$documentId,'vehicle'=>$vehicleId]);$type=$s->fetchColumn();if($type===false){$pdo->rollBack();return false;}$d=$pdo->prepare('DELETE FROM vehicle_documents WHERE id=:document AND vehicle_id=:vehicle');$d->execute(['document'=>$documentId,'vehicle'=>$vehicleId]);self::history($pdo,$vehicleId,'document_deleted','Document supprimé : '.$type,['document_id'=>$documentId]);$pdo->commit();return true;}catch(Throwable $e){if($pdo->inTransaction()){$pdo->rollBack();}throw $e;}}
    private static function params(array $d): array{$fields=['registration_number','brand','model','vehicle_type','manufacture_year','color','capacity_value','capacity_unit','mileage_km','status','assigned_driver_id','available_from','notes'];$p=[];foreach($fields as $f){$v=trim((string)($d[$f]??''));$p[$f]=$v===''?null:$v;}$p['registration_number']=mb_strtoupper((string)$p['registration_number']);$p['assigned_driver_id']=$p['assigned_driver_id']!==null?(int)$p['assigned_driver_id']:null;return $p;}
    private static function nextCode(PDO $pdo): string{return 'VEH-'.str_pad((string)((int)$pdo->query('SELECT COALESCE(MAX(id),0)+1 FROM vehicles')->fetchColumn()),5,'0',STR_PAD_LEFT);}
    private static function history(PDO $pdo,int $id,string $action,string $description,?array $changes): void{$s=$pdo->prepare('INSERT INTO vehicle_history (vehicle_id,user_id,action,description,changes_json) VALUES (:id,:user,:action,:description,:changes)');$s->execute(['id'=>$id,'user'=>Auth::id(),'action'=>$action,'description'=>$description,'changes'=>$changes?json_encode($changes,JSON_UNESCAPED_UNICODE):null]);}
    private static function nullable($v){$v=trim((string)$v);return $v===''?null:$v;}
}
