<section class="page-heading report-heading">
    <div><span class="eyebrow">CENTRE DE DÉCISION</span><h1><?= $reportView==='executive'?'Rapport exécutif':'Pilotage manager' ?></h1><p><?= $reportView==='executive'?'Vision consolidée de la performance, des tendances et des risques.':'Priorités opérationnelles, anomalies et actions à engager.' ?></p></div>
    <form method="get" class="report-period" data-no-confirm><input type="hidden" name="view" value="<?= htmlspecialchars($reportView,ENT_QUOTES,'UTF-8') ?>"><label for="reportPeriod">Période</label><select id="reportPeriod" name="period" onchange="this.form.submit()"><option value="7" <?= $period===7?'selected':'' ?>>7 jours</option><option value="30" <?= $period===30?'selected':'' ?>>30 jours</option><option value="90" <?= $period===90?'selected':'' ?>>90 jours</option><option value="365" <?= $period===365?'selected':'' ?>>12 mois</option></select></form>
</section>
<nav class="report-view-tabs" aria-label="Type de rapport"><a class="<?= $reportView==='executive'?'active':'' ?>" href="<?= $baseUrl ?>/reports?view=executive&amp;period=<?= $period ?>"><i data-lucide="landmark"></i><span><strong>Vue CEO</strong><small>Synthèse et tendances</small></span></a><a class="<?= $reportView==='manager'?'active':'' ?>" href="<?= $baseUrl ?>/reports?view=manager&amp;period=<?= $period ?>"><i data-lucide="list-checks"></i><span><strong>Vue Manager</strong><small>Alertes et exécution</small></span></a><span>Actualisé le <?= date('d/m/Y à H:i') ?></span></nav>
<section class="report-kpis executive-kpis">
<?php foreach([['clipboard-list','Courses planifiées',(int)$summary['planned'],'planned_change',''],['package-check','Courses livrées',(int)$summary['delivered'],'delivered_change',''],['gauge','Taux de réalisation',(float)$summary['completion_rate'],'completion_rate_change',' %'],['clock-check','Ponctualité',(float)$summary['punctuality_rate'],'punctuality_rate_change',' %']] as $index=>$kpi): $change=$summary[$kpi[3]]; ?>
    <article tabindex="0" role="button" data-report-detail="<?= ['planned','delivered','completion','punctuality'][$index] ?>"><span class="<?= $index===1?'success':'' ?>"><i data-lucide="<?= $kpi[0] ?>"></i></span><div><small><?= $kpi[1] ?></small><strong><?= number_format($kpi[2],$index>1?1:0,',',' ') ?><?= $kpi[4] ?></strong><em class="<?= $change!==null&&$change<0?'down':'up' ?>"><?= $change===null?'Sans comparaison':(($change>0?'+':'').number_format($change,1,',',' ').' % vs période précédente') ?></em></div><i class="report-open-icon" data-lucide="maximize-2"></i></article>
<?php endforeach; ?>
</section>
<?php if($reportView==='executive'): ?>
<section class="executive-insights"><header><i data-lucide="sparkles"></i><div><strong>À retenir</strong><small>Les trois informations prioritaires de la période</small></div></header><?php foreach($insights as $insight): ?><article class="<?= $insight['tone'] ?>"><span></span><div><strong><?= htmlspecialchars($insight['title'],ENT_QUOTES,'UTF-8') ?></strong><p><?= htmlspecialchars($insight['text'],ENT_QUOTES,'UTF-8') ?></p></div></article><?php endforeach; ?></section>
<section class="report-layout executive-layout">
    <article class="panel report-trend-panel"><header><div><h2>Activité et réalisation</h2><p>Cliquez sur un point pour afficher les courses du jour</p></div></header><div class="report-chart"><canvas id="executiveTrendChart"></canvas></div></article>
    <article class="panel report-client-panel"><header><div><h2>Performance par client</h2><p>Cliquez sur un client pour consulter ses courses</p></div></header><div class="report-client-list"><?php if(!$clients): ?><p class="report-empty">Aucune course sur cette période.</p><?php endif; ?><?php foreach($clients as $client): ?><div role="button" tabindex="0" data-report-detail="client" data-report-value="<?= htmlspecialchars($client['company_name'],ENT_QUOTES,'UTF-8') ?>"><strong><?= htmlspecialchars($client['company_name'],ENT_QUOTES,'UTF-8') ?></strong><span><?= (int)$client['delivered'] ?>/<?= (int)$client['deliveries'] ?> livrées</span><div><i style="width:<?= min(100,(float)$client['completion_rate']) ?>%"></i></div><b><?= number_format((float)$client['completion_rate'],1,',',' ') ?> %</b></div><?php endforeach; ?></div></article>
</section>
<?php else: ?>
<section class="manager-actions">
    <a class="<?= (int)$actions['overdue']?'critical':'' ?>" href="#" data-report-detail="overdue"><span><i data-lucide="alarm-clock"></i></span><div><strong><?= (int)$actions['overdue'] ?></strong><small>Livraisons en retard</small></div><i data-lucide="maximize-2"></i></a>
    <a class="<?= (int)$actions['unassigned']?'warning':'' ?>" href="#" data-report-detail="unassigned"><span><i data-lucide="user-round-x"></i></span><div><strong><?= (int)$actions['unassigned'] ?></strong><small>Courses non affectées</small></div><i data-lucide="maximize-2"></i></a>
    <a class="<?= (int)$actions['incidents']?'critical':'' ?>" href="#" data-report-detail="incidents"><span><i data-lucide="triangle-alert"></i></span><div><strong><?= (int)$actions['incidents'] ?></strong><small>Incidents ouverts</small></div><i data-lucide="maximize-2"></i></a>
    <a class="<?= (int)$actions['discrepancies']?'warning':'' ?>" href="#" data-report-detail="discrepancies"><span><i data-lucide="package-search"></i></span><div><strong><?= (int)$actions['discrepancies'] ?></strong><small>Livraisons avec écarts</small></div><i data-lucide="maximize-2"></i></a>
</section>
<section class="report-layout manager-layout">
    <article class="panel manager-priority-panel"><header><div><h2>Actions requises</h2><p>Courses en retard classées par priorité</p></div><a href="<?= $baseUrl ?>/deliveries">Toutes les livraisons</a></header><div class="manager-priority-list"><?php if(!$attention): ?><p class="report-empty">Aucune action urgente. L’exploitation est à jour.</p><?php endif; ?><?php foreach($attention as $delivery): ?><a href="<?= $baseUrl ?>/deliveries/<?= (int)$delivery['id'] ?>"><span class="priority-dot <?= strtolower($delivery['priority']) ?>"></span><div><strong><?= htmlspecialchars($delivery['reference'],ENT_QUOTES,'UTF-8') ?> · <?= htmlspecialchars($delivery['company_name'],ENT_QUOTES,'UTF-8') ?></strong><small><?= htmlspecialchars($delivery['destination']?:'Destination à confirmer',ENT_QUOTES,'UTF-8') ?> · <?= htmlspecialchars($delivery['status'],ENT_QUOTES,'UTF-8') ?></small></div><b><?= (int)$delivery['delay_minutes']>=60?floor((int)$delivery['delay_minutes']/60).' h ':'' ?><?= (int)$delivery['delay_minutes']%60 ?> min</b><i data-lucide="chevron-right"></i></a><?php endforeach; ?></div></article>
    <article class="panel report-recent-panel"><header><div><h2>Derniers déchargements</h2><p>Remises réalisées et contrôles</p></div></header><div class="report-delivery-list"><?php if(!$recentDeliveries): ?><p class="report-empty">Aucune livraison réalisée.</p><?php endif; ?><?php foreach($recentDeliveries as $delivery): ?><a href="<?= $baseUrl ?>/deliveries/<?= (int)$delivery['id'] ?>"><span class="report-delivery-icon"><i data-lucide="check"></i></span><div><strong><?= htmlspecialchars($delivery['delivered_summary'],ENT_QUOTES,'UTF-8') ?> chez <?= htmlspecialchars($delivery['company_name'],ENT_QUOTES,'UTF-8') ?></strong><small><?= date('d/m/Y à H:i',strtotime($delivery['delivered_at'])) ?> · <?= htmlspecialchars($delivery['reference'],ENT_QUOTES,'UTF-8') ?></small></div><?php if((int)$delivery['differences']>0): ?><em><?= (int)$delivery['differences'] ?> écart(s)</em><?php else: ?><em class="conform">Conforme</em><?php endif; ?></a><?php endforeach; ?></div></article>
</section>
<?php endif; ?>
<script>window.MSS_REPORT=<?= json_encode(['trend'=>$trend,'view'=>$reportView],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script>
<div class="report-detail-modal" id="reportDetailModal" hidden aria-hidden="true"><button type="button" class="report-modal-backdrop" data-report-close aria-label="Fermer"></button><section role="dialog" aria-modal="true" aria-labelledby="reportDetailTitle"><header><div><small>DÉTAIL DU RAPPORT</small><h2 id="reportDetailTitle">Chargement…</h2><p id="reportDetailCount"></p></div><div><a id="reportDetailExport" class="button button-secondary" href="#"><i data-lucide="sheet"></i> Exporter Excel</a><button type="button" class="icon-button" data-report-close aria-label="Fermer"><i data-lucide="x"></i></button></div></header><div class="report-modal-body" id="reportDetailBody"><span class="report-modal-loading">Chargement des données…</span></div></section></div>
